site_name: Metadata Schema for Data Concerning Chemicals in the Outdoor Environment
site_url: https://katarinari.github.io/datasteward_final_project/
theme:
  name: material
docs_dir: docs

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - nl2br
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js